### ISSUE TITLE
Timer still counts down in logged out session

### ISSUE THREAD

**Issue by CyberneticNomad-v808** [changhuixu/session-expiration-alert#6] opened 2020-03-30 18:13 UTC
To replicate:

1. Start a session
2. Let it expire and sign user out
3. Wait for the configured time to expire again
4. Observe that the the modal pops up to alert to the session ending.

**Comment by changhuixu** [comment] 2020-03-30 21:22
Hi @BLKingLLC , I am sorry that I couldn't reproduce what you have described.
The logout button will unsubscribe the timer. I don't think the modal will open again, unless the page refreshes. Or maybe I missed something here.
Please add comments if you have more information. Thank you.

**Comment by CyberneticNomad-v808** [comment] 2020-03-30 22:04
@changhuixu It seems to work properly when you click the logout button, but not when you simply let it expire.

**Comment by changhuixu** [comment] 2020-03-30 22:39
It should not happen either. I am not able to see the modal dialog opens again.

The code below shows the cleanup steps when the modal is expired if no intervention.

https://github.com/changhuixu/session-expiration-alert/blob/9126d6248331c36c5906f25289f61f73d9bce7a9/projects/session-expiration-alert/src/lib/components/session-expiration-alert/session-expiration-alert.component.ts#L61-L67

**Comment by CyberneticNomad-v808** [comment] 2020-03-31 17:22
I'm still getting it, but I guess it could be an artifact of my installation.

**Comment by changhuixu** [comment] 2020-04-01 12:32
I will close this issue for now. Let me know if you find other things. Thanks.

**Closed as completed by changhuixu** 2020-04-01 12:32 UTC
